//GettinG Tab Value
export const GET_TABVALUE_REQUEST = "GET_TABVALUE_REQUEST"
export const GET_TABVALUE_SUCCESS = "GET_TABVALUE_SUCCESS"
export const GET_TABVALUE_FAILURE = "GET_TABVALUE_FAILURE"

export const GET_PDFVALUE_REQUEST = "GET_PDFVALUE_REQUEST"
export const GET_PDFVALUE_SUCCESS = "GET_PDFVALUE_SUCCESS"
export const GET_PDFVALUE_FAILURE = "GET_PDFVALUE_FAILURE"




